stages: 
  - build
  - test
  - deploy

.before_script_ssh_setup: &before_script_ssh_setup
  - 'command -v ssh-agent >/dev/null || ( apt-get upfdate -y && apt-get inteall openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh- add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/./known_hosts

build-job:
 stage: build
 script:
    - echo "Bygger projektet..."
    - sleep 2

lint-job:
imgae: node:20
stage: test
script: 
    - npm install
    - npm run lint

manual_approval_step:
 stage: deploy
 script: 
    - echo "Väntar på manuellt godkännande innan deploy..."
 when: manual
 only: 
  - main

deploy_production_job:
  stage: deploy
  environment:
    name: produkction
    url: http://$PRODUCTION_HOST
  variables:
  variables:
    REMOTE_HOST: $PRODUCTION_HOST
    DOCKER_HOST: ssh://ubuntu@$REMOTE_HOST
    NODE_ENV: "production"
    PORT: 3000
    MONGO_URI: "mongodb://mongo:27017/"
    SESSION_SECRET: $SESSION_SECRET
    DOCKER_HOST_PORT: $DOCKER_PORT
  before_script: *before_script_ssh_setup
  image: docker:latest
  script: 
    - echo "Deployar till produktion..."
    - docker compose -f docker-compose.production.yaml --build -d
  only:
    - main
  needs:
    - manual_approval_step