stages:
  - build
  - deploy_staging
  - deploy_production

variables:
  # Disable TLS to avoid connection issues between Docker client and daemon
  DOCKER_TLS_CERTDIR: ""
  # Define the Docker host for communication between the client and daemon
  DOCKER_HOST: tcp://docker:2375
  # Use overlay2 as the Docker storage driver
  DOCKER_DRIVER: overlay2

# Build the Docker images
build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--privileged"]
  script:
    # Log in to the Docker registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Build and push the main Docker image
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} -f Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    # Build and push the production Docker image
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-prod -f Dockerfile.production .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-prod
  only:
    - main

# Deploy to staging server (automatically)
deploy_staging:
  stage: deploy_staging
  image: alpine:latest
  script:
    # Install SSH client
    - apk add --no-cache openssh-client bash

    # Set up SSH for secure deployment
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $STAGING_HOST >> ~/.ssh/known_hosts

    # Deploy using docker-compose
    - |
      ssh -i ~/.ssh/id_rsa ubuntu@$STAGING_HOST "
        mkdir -p ~/app && cd ~/app
        export IMAGE_TAG=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
        export DOCKER_PORT=${DOCKER_PORT:-8080}
        export SESSION_SECRET=${SESSION_SECRET}
        docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
        docker pull $IMAGE_TAG
        docker-compose down
        docker-compose up -d
      "
  environment:
    name: staging
    url: http://$STAGING_HOST:${DOCKER_PORT:-8080}
  only:
    - main

# Deploy to production server (manual trigger)
deploy_production:
  stage: deploy_production
  image: alpine:latest
  script:
    # Install SSH client
    - apk add --no-cache openssh-client bash

    # Set up SSH for secure deployment
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $PRODUCTION_HOST >> ~/.ssh/known_hosts

    # Deploy using docker-compose
    - |
      ssh -i ~/.ssh/id_rsa ubuntu@$PRODUCTION_HOST "
        mkdir -p ~/app-production && cd ~/app-production
        export IMAGE_TAG=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-prod
        export DOCKER_PORT=${DOCKER_PORT:-80}
        export SESSION_SECRET=${SESSION_SECRET}
        docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
        docker pull $IMAGE_TAG
        docker-compose down
        docker-compose up -d
      "
  environment:
    name: production
    url: http://$PRODUCTION_HOST:${DOCKER_PORT:-80}
  when: manual
  only:
    - main
