services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - BASE_URL=/
    command: npm run dev

  mongo:
    ports:
      - "27017:27017"  # Expose MongoDB port for local development tools